package xboxgamepassgenerator;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.util.Random;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        buttonGroup_Month = new javax.swing.ButtonGroup();
        buttonGroup_GamePass = new javax.swing.ButtonGroup();
        jRadioButton_1Month = new javax.swing.JRadioButton();
        jRadioButton_3Month = new javax.swing.JRadioButton();
        jRadioButtonPC = new javax.swing.JRadioButton();
        jRadioButtonUltimate = new javax.swing.JRadioButton();
        jRadioButtonConsole = new javax.swing.JRadioButton();
        jProgressBar = new javax.swing.JProgressBar();
        jScrollPane = new javax.swing.JScrollPane();
        jTextCode = new javax.swing.JTextArea();
        jButtonGenerate = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Xbox Game Pass Generator");
        setResizable(false);

        buttonGroup_Month.add(jRadioButton_1Month);
        jRadioButton_1Month.setText("1 MONTH");

        buttonGroup_Month.add(jRadioButton_3Month);
        jRadioButton_3Month.setText("3 MONTH");

        buttonGroup_GamePass.add(jRadioButtonPC);
        jRadioButtonPC.setText("PC");

        buttonGroup_GamePass.add(jRadioButtonUltimate);
        jRadioButtonUltimate.setText("ULTIMATE");

        buttonGroup_GamePass.add(jRadioButtonConsole);
        jRadioButtonConsole.setText("CONSOLE");

        jTextCode.setColumns(20);
        jTextCode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextCode.setRows(5);
        jScrollPane.setViewportView(jTextCode);

        jButtonGenerate.setText("GENERATE");
        jButtonGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerateActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("X360 by Redge", 0, 36)); // NOI18N
        jLabelTitle.setText("XBOX GAME PASS GENERATOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonPC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButton_1Month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(164, 164, 164)
                        .addComponent(jRadioButtonConsole)
                        .addGap(161, 161, 161)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton_3Month, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(89, 89, 89))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButtonUltimate)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 792, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelTitle)
                                        .addGap(98, 98, 98)))))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(jButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_1Month)
                    .addComponent(jRadioButton_3Month))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPC)
                    .addComponent(jRadioButtonConsole)
                    .addComponent(jRadioButtonUltimate))
                .addGap(18, 18, 18)
                .addComponent(jButtonGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButtonGenerateActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Create optionGroups
        ButtonGroup optionGroup1 = buttonGroup_GamePass;
        ButtonGroup optionGroup2 = buttonGroup_Month;
        
        // Any option, show message
        if(optionGroup1.getSelection() == null && optionGroup2.getSelection() == null || optionGroup1.getSelection() == null || optionGroup2 == null){
            JOptionPane.showMessageDialog(null, "Please, select your month and game pass", "Xbox Game Pass Generator", JOptionPane.INFORMATION_MESSAGE);
        }else{
            // Var codeLenght
            int codeLenght = 25;
            
            // Var characters
            String characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
           
            // Random function
            Random random = new Random();
            
            // Var StringBuilder code
            StringBuilder code = new StringBuilder();
            
            // Generate code
            for(int i = 0; i < codeLenght; i++){
                int randomIndex = random.nextInt(characters.length());
                char randomChar = characters.charAt(randomIndex);
                
                // Set character to code
                code.append(randomChar);
                
                // Set progressBar
                jProgressBar.setValue((i + 1) * 100 / codeLenght);
            }
            
                // FormattedCode (XXXXX-XXXXX-XXXXX-XXXXX-XXXXX)
                String formattedCode = String.format(
                "%s-%s-%s-%s-%s",
                code.substring(0, 5),
                code.substring(5, 10),
                code.substring(10, 15),
                code.substring(15, 20),
                code.substring(20, 25)  
                );
            JOptionPane.showMessageDialog(null, "GENERATED! COPIED TO CLIPBOARD. CONGRATULATIONS! :D", "Xbox Game Pass Generator", JOptionPane.INFORMATION_MESSAGE);
            
            // Set progess bar to 0;
            jProgressBar.setValue(0);
            
            // Set code text
            jTextCode.setText(formattedCode);
            
            // Set code to Clipboard
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            StringSelection stringSelection = new StringSelection(formattedCode);
            clipboard.setContents(stringSelection, null);
            
            // Clear selection
            optionGroup1.clearSelection();
            optionGroup2.clearSelection();
        }
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        FlatDarkLaf.setup();
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.ButtonGroup buttonGroup_GamePass;
    private javax.swing.ButtonGroup buttonGroup_Month;
    private javax.swing.JButton jButtonGenerate;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonConsole;
    private javax.swing.JRadioButton jRadioButtonPC;
    private javax.swing.JRadioButton jRadioButtonUltimate;
    private javax.swing.JRadioButton jRadioButton_1Month;
    private javax.swing.JRadioButton jRadioButton_3Month;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextCode;
    // End of variables declaration                   
}
